### PR TITLE
TASK: Prefer installing of neos and flowpack packages from source

### PR DESCRIPTION
**Pull request by mficzel**
Since this is the development distribution for neos composer should install all neos packages from source.

Since quite some packages in the flowpack namespace are maintained by neos team members and some are
even installed in a default neos it makes our life easier to install packages from source in the development distribution aswell.

See https://getcomposer.org/doc/06-config.md#preferred-install

Resolves: #70

### CODE REVIEW

**Review by kdambekalns — COMMENTED** [review]
While this is pretty specific, I usually want dev versions of Flowpack or other packages downloaded as source, too. I'd personally prefer a generic `auto` setting in the distributions…

**Comment by mficzel** [comment]
In the end it is the neos dev dist that is why i considered it fair to set the config for neos/*. 
Adding `"*":"auto"` in the base dists and `"*" : "source"` for dev-dists would be fine for me aswell.

**Comment by kdambekalns** [comment]
> `"*" : "source"` for dev-dists would be fine for me aswell.

Oh no! Having Symfony, Doctrine, … as source would not be what I want!

**Comment by mficzel** [comment]
Thinking about it tend to not like the idea to force composer into a legacy mode with *:auto. often it is best to configure which is important (version control in a dev dist) and leave the rest to the infrastructure.

**Comment by kdambekalns** [comment]
> into a legacy mode

I am rather unhappy with their choice of wording, TBH. If this was really legacy, they could have named the mode `legacy`. For me, it does a very logical thing. But that's another story. 🙃

**Comment by mficzel** [comment]
We can add `*:auto` to dev-dists as those can always be changed. I just would not like it on the base-dists. However `neos/*:source` imho still makes sense for dev-dists anyways.

**Review by daniellienert — APPROVED** [review]
Makes sens. 

Maybe `"flowpack/*": "source"` would also be reasonable

**Comment by mficzel** [comment]
@daniellienert added `"flowpack/*":"source"` as suggested ... makes sense and life easier for ourself.

**Review by albe — APPROVED** [review]
Makes sense as far as I can tell. I'm not sure about the `*:auto` part but I see the argument that "legacy" is probably a bad framing. It's a "no thoughts needed" mode? Let's decide on that independent of this, since afais we agree that neos/* and flowpack/* should be "source"

**Pull request merged**
