### PR TITLE
TASK: "git add" Neos and Media documentation changes

### PR DESCRIPTION
**Pull request by kdambekalns**
Instead of adding all changes (potentially unintended), just add what
has been changed in Neos.Neos/Documentation and Neos.Media/Documentation.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Done against 5.3 since we still run the related jobs automatically…

**Comment by kdambekalns** [comment]
The changes are only supposed to be in Neos.Neos and Neos.Media, see https://github.com/neos/neos-development-collection/search?l=YAML&q=DocTools

**Comment by kdambekalns** [comment]
When this is merged, drop the requirement for `neos/doctools` from https://github.com/neos/neos-development-distribution/blob/b5bdfd1072bf6dc497c577be126d6793f544d1ee/composer.json#L49 an upwards…

**Review by kitsunet — APPROVED** [review]
Yes!

**Pull request merged**
