### PR TITLE
TASK: Benchmark basics

### PR DESCRIPTION
**Pull request by kitsunet**
Introduces a phpbench.json with configuration for phpbench and a composer script to execute the benchmarks.

PhpBench is to be installed via `phive install phpbench`

Relates: neos/flow-development-collection#3361
Relates: neos/BuildEssentials#71

### CODE REVIEW

**Comment by kitsunet** [comment]
We could also put the phpbench.json into the BuildEssentials.... Matter of choice really. I wouldn't mind either way. Any opionions.

**Comment by kitsunet** [comment]
Unfortunately using the `config` option for phpbench doesn't seem to work with relative paths?!? So moving it out is not feasible as we cannot know the absolute path (which does work). But renamed to phpbench.json.dist as that is taken as fallback and makes more sense. Also I just realized I need to make the same change in the flow-dev-distribution.... But for now Neos is a good starting point...

**Review by bwaidelich — APPROVED** [review]

**Comment by kdambekalns** [comment]
What is `phive`? Ah: https://phar.io/ (and some more details at https://php.watch/articles/phive)

Why that? Why not via composer?

**Comment by kitsunet** [comment]
I do not want the dependency in the project, it makes no sense for tools like this IMHO. All build tools should rather come as phar to be independent of the codebase. Although phive has it#s problems (mainly missing maintenance atm). But I would still suggest ot anyone to install this as phar. But sure we can still decide to add it as require-dev in the future

**Comment by kdambekalns** [comment]
> All build tools should rather come as phar to be independent of the codebase.

In theory yes, in practice that caused problems in the past, whenever you had differences in PHP versions e.g. that broke things. Seeing that `phive` supports multiple / specific versions that might be a solution, though.

I was just a bit surprised, had never heard of the tool and wonder if we need to add some pointers or hints to some documentation?

**Comment by ahaeslich** [comment]
> and wonder if we need to add some pointers or hints to some documentation?

@kitsunet and I discussed this briefly and wondered where a good place would be for this.

**Comment by kdambekalns** [comment]
> > and wonder if we need to add some pointers or hints to some documentation?
> 
> @kitsunet and I discussed this briefly and wondered where a good place would be for this.

We could add it `CONTRIBUTING.md`… after this is merged: https://github.com/neos/neos-development-collection/pull/5137 😎

**Pull request merged**
